version: "3.8"
services:
  teamsexample:
    container_name: teams-app
    image: teams
    restart: always
    build: .
    ports:
      - 8081:8081
    environment:
      MYSQL_HOST: mysqlteams
      MYSQL_USER: root
      MYSQL_PASSWORD: Root
      MYSQL_PORT: 3306
  mysqlteams:
    container_name: mysqlteams
    image: mysql
    ports:
      - 3301:3306    
    environment:
      MYSQL_DATABASE: teams
      MYSQL_ROOT_PASSWORD: Root
