server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: employee-service
        uri: lb://employee-service
        predicates:
        - Path=/employee/**
      - id: department-service
        uri: lb://department-service
        predicates:
        - Path=/department/**
        


