version: "3.8"
services:
  playersexample:
    container_name: players-app
    image: players
    restart: always
    build: .
    ports:
      - 8082:8082
    environment:
      MYSQL_HOST: mysqlplayers
      MYSQL_USER: root
      MYSQL_PASSWORD: Root
      MYSQL_PORT: 3306
  mysqlplayers:
    container_name: mysqlplayers
    image: mysql
    ports:
      - 3302:3306    
    environment:
      MYSQL_DATABASE: players
      MYSQL_ROOT_PASSWORD: Root
   