version: "3.8"
services:
  dockercomposeexample:
    container_name: spring-app
    image: dockercomposeexample
    restart: always
    build: .
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: mysqldbs
      MYSQL_USER: root
      MYSQL_PASSWORD: Root
      MYSQL_PORT: 3306
  mysqldbs:
    container_name: mysqldbs
    image: mysql
    ports:
      - 3308:3306    
    environment:
      MYSQL_DATABASE: student
      MYSQL_ROOT_PASSWORD: Root
   